[project]
name = "mediapipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "protobuf>=6.33.1",
    "streamlit>=1.51.0",
]
